version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
  depends_on:
      - db
  environment:
    DATABASE_URL: "mysql://user:password@tcp(db:3306)/forum"

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: forum
    ports:
      - "3306:3306"
  volumes:
    - db-data:/var/lib/mysql

volumes:
  db-data: